apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: deployment
  labels:
    app: in-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster
  template:
    metadata:
      labels:
        app: in-cluster
    spec:
      containers:
      - name: in-cluster
        image: in-cluster:latest
        args:
          - test1
          - test2
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        metadata:
          labels:
            - in-cluster
        resources:
          limits:
            memory: 0.5G
            cpu: 1000m
